name: croppy
description: A fully customizable image cropper for Flutter. Mobile-first, but supports Web and Desktop platforms.
version: 1.1.4
homepage: https://github.com/kekland/croppy

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cassowary: ^0.4.2

  plugin_platform_interface: ^2.0.2
  ffi: 2.0.2

  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: 7.2.11

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      web: 


